######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 3 23:12:43 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h ../jungle-board.h ../jungle-search.h
FORMS += settings_dialogue.ui
SOURCES += ../jungle-board.c ../jungle-search.c jungle-ui.cpp
